#!/bin/bash -login
#PBS -l walltime=24:00:00,nodes=1:ppn=1,mem=8gb
#PBS -M annat.haber@jax.org
#PBS -m abe
#PBS -j oe

cd ${PBS_O_WORKDIR} 

module load bcftools/1.3.1

InPath=/sdata/carter-lab/carter/AMPAD/WGS_PrelimProcessing/output/Joint/MAF05

bcftools query -f '[%CHROM\t%POS\t%REF\t%ALT\t%SAMPLE\t%GT\n]' -i 'POS=@ADvariantsPOS.txt' $InPath/inputvcf > \
                $InPath/ADvariants/allADVariants_genotypes.txt
 			
